from typing import Any, Protocol


class AgentRepositoryProtocol(Protocol):
    def list_agents(self) -> list[dict[str, Any]]: ...

    def get_agent(self, agent_id: str) -> tuple[dict[str, Any] | None, list[dict[str, Any]]]: ...

    def upsert_agent(self, agent_id: str | None, hostname: str, username: str, distribution: str) -> str: ...

    def update_config(self, agent_id: str, jitter: int, beacon_interval: int) -> None: ...

    def set_status(self, agent_id: str, status: str) -> None: ...
