from typing import Any, Protocol


class TaskRepositoryProtocol(Protocol):
    def pending_task_for(self, agent_id: str) -> tuple[dict[str, Any] | None, dict[str, Any] | None]: ...

    def enqueue(self, task_id: str, agent_id: str, name: str, code: str, sched_type: str, sched_val: str, duration: int, status: str = 'Pending') -> None: ...

    def update_result(self, task_id: str, status: str, output: str) -> None: ...

    def list_tasks(self, agent_id: str) -> list[dict[str, Any]]: ...

    def create_workflow(self, workflow_id: str, agent_id: str, name: str, definition: dict[str, Any]) -> dict[str, Any]: ...

    def list_workflows(self, agent_id: str) -> list[dict[str, Any]]: ...

    def store_collected_data(self, agent_id: str, task_id: str | None, workflow_id: str | None, data_type: str, schema_version: int, payload: dict[str, Any], collected_at: str | None = None) -> dict[str, Any]: ...

    def list_collected_data(self, agent_id: str) -> list[dict[str, Any]]: ...
